spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///todolist
    username: root
    password: root
  redis:
    port: 6379
    host: localhost
    password: elitehzy